// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Screenshot1.tsx": () => import("../components/mockups/Screenshot1.tsx"),
  "./components/mockups/Screenshot2.tsx": () => import("../components/mockups/Screenshot2.tsx"),
  "./components/mockups/Screenshot3.tsx": () => import("../components/mockups/Screenshot3.tsx")
};
